### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by andim27** [KhilanVitthani/flutter_social_share_plugin#1]
Please add share to Instagram, Viber and other popular app, share by sms, by email etc,  thank's
Also update to the last gradle rules because error:
```
flutter_social_share_plugin-1.0.3/android/src/main/java/com/example/flutter_social_share/FlutterSocialSharePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by KhilanVitthani** [comment]
Instagram,Sms,and email share added check with version [flutter_social_share_plugin:2.0.0](https://pub.dev/packages/flutter_social_share_plugin)
