### ISSUE TITLE
Conflict with flutter_facebook_auth: 7.0.0 and above

### ISSUE THREAD

**Issue by Heatclift** [KhilanVitthani/flutter_social_share_plugin#4]
When using the latest version of flutter_facebook_auth, iOS won't compile.

![Screenshot 2024-10-25 at 1 04 19 AM](https://github.com/user-attachments/assets/42b5854a-8807-48c3-81ad-62a8a1bf8c96)

**Comment by Heatclift** [comment]
"Fixes Heatclift:main"

**Comment by Heatclift** [comment]
FIx: #3

**Comment by KhilanVitthani** [comment]
A pull request is merged.
