### ISSUE TITLE
Check deprecated code

### ISSUE THREAD

**Issue by andim27** [KhilanVitthani/flutter_social_share_plugin#5]
If build on flutter 3.27.0
ERROR(Warning): 
`flutter_social_share_plugin-2.1.0/android/src/main/java/com/example/flutter_social_share/FlutterSocialSharePlugin.java uses or overrides a deprecated API. `

Please try build and update plugin. 
Plugin is useful it would like to have the actual version

**Comment by KhilanVitthani** [comment]
Fix in [v2.1.1](https://pub.dev/packages/flutter_social_share_plugin/versions/2.1.1)
